file:
  directory: D:\Students\jang jin seong\download\greengram_ver3

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: GreenGramVer2
  datasource:
    username: root
    password: green502
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3
    #url: jdbc:mariadb://localhost/greengram_ver2 기존꺼
    # 위처럼 log4jdbc를 넣어줘야 쿼리문의 로그가 찍힘
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # 이것도 같이 작성 해줘야 됨
  servlet:
    multipart:
      max-file-size: 15MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true

